"""add corruption col to base mechanics

Revision ID: 375c38ce0d9d
Revises: a9937d4c5443
Create Date: 2024-12-05 22:13:39.896726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '375c38ce0d9d'
down_revision: Union[str, None] = 'a9937d4c5443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_mechanics', sa.Column('corruption', sa.Integer()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_mechanics', 'corruption')
    # ### end Alembic commands ###
