"""add characteristics tag

Revision ID: 9a2d8ad6e86b
Revises: 6c7cd4f9591c
Create Date: 2024-12-28 09:10:42.584916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a2d8ad6e86b'
down_revision: Union[str, None] = '6c7cd4f9591c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attributes', sa.Column('ws_class_trait', sa.Boolean()))
    op.add_column('attributes', sa.Column('bs_class_trait', sa.Boolean()))
    op.add_column('attributes', sa.Column('s_class_trait', sa.Boolean()))
    op.add_column('attributes', sa.Column('t_class_trait', sa.Boolean()))
    op.add_column('attributes', sa.Column('i_class_trait', sa.Boolean()))
    op.add_column('attributes', sa.Column('ag_class_trait', sa.Boolean()))
    op.add_column('attributes', sa.Column('dex_class_trait', sa.Boolean()))
    op.add_column('attributes', sa.Column('int_class_trait', sa.Boolean()))
    op.add_column('attributes', sa.Column('wp_class_trait', sa.Boolean()))
    op.add_column('attributes', sa.Column('fel_class_trait', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attributes', 'fel_class_trait')
    op.drop_column('attributes', 'wp_class_trait')
    op.drop_column('attributes', 'int_class_trait')
    op.drop_column('attributes', 'dex_class_trait')
    op.drop_column('attributes', 'ag_class_trait')
    op.drop_column('attributes', 'i_class_trait')
    op.drop_column('attributes', 't_class_trait')
    op.drop_column('attributes', 's_class_trait')
    op.drop_column('attributes', 'bs_class_trait')
    op.drop_column('attributes', 'ws_class_trait')
    # ### end Alembic commands ###
