"""add skill tags

Revision ID: b14a806c1b5b
Revises: 9a2d8ad6e86b
Create Date: 2025-01-02 07:50:30.667894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14a806c1b5b'
down_revision: Union[str, None] = '9a2d8ad6e86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basic_skill', sa.Column('tag', sa.Integer(),))
    op.add_column('skill', sa.Column('tag', sa.Integer(),))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill', 'tag')
    op.drop_column('basic_skill', 'tag')

    # ### end Alembic commands ###
