"""Initial database schema with all tables

Revision ID: initial_001
Revises:
Create Date: 2025-12-11 11:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "initial_001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('career', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('careerpath', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('hair', sa.String(), nullable=False),
    sa.Column('eyes', sa.String(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('silver', sa.Integer(), nullable=False),
    sa.Column('brass', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_mechanics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('experience_spent', sa.Integer(), nullable=False),
    sa.Column('movement', sa.Integer(), nullable=False),
    sa.Column('fate_points', sa.Integer(), nullable=False),
    sa.Column('fortune_points', sa.Integer(), nullable=False),
    sa.Column('resilience', sa.Integer(), nullable=False),
    sa.Column('resolve', sa.Integer(), nullable=False),
    sa.Column('motivation', sa.Integer(), nullable=False),
    sa.Column('corruption', sa.Integer(), nullable=False),
    sa.Column('mutations', sa.Integer(), nullable=False),
    sa.Column('mental_mutations', sa.Integer(), nullable=False),
    sa.Column('physical_mutations', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    op.create_table('text_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('psychology', sa.String(), nullable=False),
    sa.Column('health_notes', sa.String(), nullable=False),
    sa.Column('short_term_ambition', sa.String(), nullable=False),
    sa.Column('long_term_ambition', sa.String(), nullable=False),
    sa.Column('doom', sa.String(), nullable=False),
    sa.Column('campaign_notes', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    op.create_table('party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('members', sa.String(), nullable=False),
    sa.Column('ambitions', sa.String(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('silver', sa.Integer(), nullable=False),
    sa.Column('brass', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('ws_base', sa.Integer(), nullable=False),
    sa.Column('ws_modifier', sa.Integer(), nullable=False),
    sa.Column('ws_bonus', sa.Integer(), nullable=False),
    sa.Column('ws_class_trait', sa.Boolean(), nullable=False),
    sa.Column('bs_base', sa.Integer(), nullable=False),
    sa.Column('bs_modifier', sa.Integer(), nullable=False),
    sa.Column('bs_bonus', sa.Integer(), nullable=False),
    sa.Column('bs_class_trait', sa.Boolean(), nullable=False),
    sa.Column('s_base', sa.Integer(), nullable=False),
    sa.Column('s_modifier', sa.Integer(), nullable=False),
    sa.Column('s_bonus', sa.Integer(), nullable=False),
    sa.Column('s_class_trait', sa.Boolean(), nullable=False),
    sa.Column('t_base', sa.Integer(), nullable=False),
    sa.Column('t_modifier', sa.Integer(), nullable=False),
    sa.Column('t_bonus', sa.Integer(), nullable=False),
    sa.Column('t_class_trait', sa.Boolean(), nullable=False),
    sa.Column('i_base', sa.Integer(), nullable=False),
    sa.Column('i_modifier', sa.Integer(), nullable=False),
    sa.Column('i_bonus', sa.Integer(), nullable=False),
    sa.Column('i_class_trait', sa.Boolean(), nullable=False),
    sa.Column('ag_base', sa.Integer(), nullable=False),
    sa.Column('ag_modifier', sa.Integer(), nullable=False),
    sa.Column('ag_bonus', sa.Integer(), nullable=False),
    sa.Column('ag_class_trait', sa.Boolean(), nullable=False),
    sa.Column('dex_base', sa.Integer(), nullable=False),
    sa.Column('dex_modifier', sa.Integer(), nullable=False),
    sa.Column('dex_bonus', sa.Integer(), nullable=False),
    sa.Column('dex_class_trait', sa.Boolean(), nullable=False),
    sa.Column('int_base', sa.Integer(), nullable=False),
    sa.Column('int_modifier', sa.Integer(), nullable=False),
    sa.Column('int_bonus', sa.Integer(), nullable=False),
    sa.Column('int_class_trait', sa.Boolean(), nullable=False),
    sa.Column('wp_base', sa.Integer(), nullable=False),
    sa.Column('wp_modifier', sa.Integer(), nullable=False),
    sa.Column('wp_bonus', sa.Integer(), nullable=False),
    sa.Column('wp_class_trait', sa.Boolean(), nullable=False),
    sa.Column('fel_base', sa.Integer(), nullable=False),
    sa.Column('fel_modifier', sa.Integer(), nullable=False),
    sa.Column('fel_bonus', sa.Integer(), nullable=False),
    sa.Column('fel_class_trait', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    op.create_table('basic_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('attribute', sa.String(), nullable=False),
    sa.Column('advances', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('attribute', sa.String(), nullable=False),
    sa.Column('advances', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('given_bonus', sa.Integer(), nullable=False),
    sa.Column('bonus_attribute', sa.String(), nullable=False),
    sa.Column('times_taken', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('armor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('encumbrance', sa.Integer(), nullable=False),
    sa.Column('armor_points', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('qualities', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weapon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('encumbrance', sa.Integer(), nullable=False),
    sa.Column('range', sa.Integer(), nullable=False),
    sa.Column('damage', sa.String(), nullable=False),
    sa.Column('qualities', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('casting_number', sa.Integer(), nullable=False),
    sa.Column('range', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('effect', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('encumbrance', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ammunition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('qualities', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('who', sa.String(), nullable=False),
    sa.Column('what', sa.String(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('silver', sa.Integer(), nullable=False),
    sa.Column('brass', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('career', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('careerpath', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cv')
    op.drop_table('ledger')
    op.drop_table('ammunition')
    op.drop_table('trapping')
    op.drop_table('magic')
    op.drop_table('weapon')
    op.drop_table('armor')
    op.drop_table('talent')
    op.drop_table('skill')
    op.drop_table('basic_skill')
    op.drop_table('attributes')
    op.drop_table('party')
    op.drop_table('text_fields')
    op.drop_table('base_mechanics')
    op.drop_table('character')
    # ### end Alembic commands ###
